---
- hosts: localhost
  vars: 
    rgname: "rg1"
  tasks:
   - name: Create a resource group
     azure_rm_resourcegroup:
      name: "{{rgname}}"
      location: "eastus"
   - name: Create virtual network vnet1
     azure_rm_virtualnetwork:
      resource_group: "{{rgname}}"
      name: "{{item}}"
      location: "eastus"
      loop:
        -h1vnet
        -s1vnet
...
