---
- hosts: localhost
  vars: 
    rgname: "rg1"
  tasks:
   - name: Create a resource group
     azure_rm_resourcegroup:
      name: "{{rgname}}"
      location: "eastus"
   - name: Create virtual network hubvnet and spokevnet
     azure_rm_virtualnetwork:
      resource_group: "{{rgname}}"
      name: "{{ item.name }}"
      location: "{{ item.location }}"
      address_prefixes: "{{ item.add_pref }}"
     loop:
       - {name: 'hubvnet', add_pref: '10.10.0.0/16', location: 'eastus'}
       - {name: 'spokevnet', add_pref: '10.10.1.0/16', location: 'eastus'}
...

