---
- hosts: localhost
  vars: 
    rgname: "rg1"
  tasks:
   - name: Create a resource group
     azure_rm_resourcegroup:
      name: "{{rgname}}"
      location: "eastus"
   - name: Create virtual network vnet1
     azure_rm_virtualnetwork:
      resource_group: "{{rgname}}"
      name: "h1Vnet"
      location: "eastus"
      address_prefixes: "10.1.0.0/16"
   - name: Create virtual network vnet2
     azure_rm_virtualnetwork:
      resource_group: "{{rgname}}"
      name: "h2Vnet"
      location: "westus"
      address_prefixes: "10.2.0.0/16"
   - name: Create virtual network vnet3
     azure_rm_virtualnetwork:
      resource_group: "{{rgname}}"
      name: "s1Vnet"
      location: "eastus"
      address_prefixes: "10.3.0.0/16"
   - name: Create virtual network vnet4
     azure_rm_virtualnetwork:
      resource_group: "{{rgname}}"
      name: "s2Vnet"
      location: "eastus"
      address_prefixes: "10.4.0.0/16"
   - name: Create virtual network vnet5
     azure_rm_virtualnetwork:
      resource_group: "{{rgname}}"
      name: "s3Vnet"
      location: "westus"
      address_prefixes: "10.5.0.0/16"
   - name: Create virtual network vnet6
     azure_rm_virtualnetwork:
      resource_group: "{{rgname}}"
      name: "s4Vnet"
      location: "westus"
      address_prefixes: "10.6.0.0/16"
   - name: Create Network Security Group that RDP
     azure_rm_securitygroup:
       resource_group: "{{ rgname}}"
       name: "h1NSG"
       location: "eastus"
       rules:
        - name: RDP
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound  
   - name: Create Network Security Group that RDP
     azure_rm_securitygroup:
       resource_group: "{{ rgname}}"
       name: "s3NSG"
       location: "westus"
       rules:
        - name: RDP
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound  
   - name: Create Network Security Group that RDP
     azure_rm_securitygroup:
       resource_group: "{{ rgname}}"
       name: "s2NSG"
       location: "eastus"       
       rules:
        - name: RDP
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound  
   - name: Create Network Security Group that RDP
     azure_rm_securitygroup:
       resource_group: "{{ rgname}}"
       name: "h2NSG"
       location: "westus"       
       rules:
        - name: RDP
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound  
   - name: Create Network Security Group that RDP
     azure_rm_securitygroup:
       resource_group: "{{ rgname}}"
       name: "s1NSG"
       location: "eastus"       
       rules:
        - name: RDP
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound            
   - name: Create Network Security Group that RDP
     azure_rm_securitygroup:
       resource_group: "{{ rgname}}"
       name: "s4NSG"
       location: "westus"       
       rules:
        - name: RDP
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound             
   - name: Add subnet 
     azure_rm_subnet:
       resource_group: "{{rgname}}"
       name: "defaultsubnet"
       address_prefix: "10.1.0.0/24"
       virtual_network: "h1Vnet"
       security_group: "h1NSG"
   - name: Add subnet 
     azure_rm_subnet:
       resource_group: "{{rgname}}"
       name: "defaultsubnet"
       address_prefix: "10.2.0.0/24"
       virtual_network: "h2Vnet"
       security_group: "h2NSG"
   - name: Add subnet 
     azure_rm_subnet:
      resource_group: "{{rgname}}"
      name: "defaultsubnet"
      address_prefix: "10.3.0.0/24"
      virtual_network: "s1Vnet"
      security_group: "s1NSG"
   - name: Add subnet 
     azure_rm_subnet:
      resource_group: "{{rgname}}"
      name: "defaultsubnet"
      address_prefix: "10.4.0.0/24"
      virtual_network: "s2Vnet"
      security_group: "s2NSG"
   - name: Add subnet 
     azure_rm_subnet:
      resource_group: "{{rgname}}"
      name: "defaultsubnet"
      address_prefix: "10.5.0.0/24"
      virtual_network: "s3Vnet"
      security_group: "s3NSG"
   - name: Add subnet 
     azure_rm_subnet:
      resource_group: "{{rgname}}"
      name: "defaultsubnet"
      address_prefix: "10.6.0.0/24"
      virtual_network: "s4Vnet"
      security_group: "s4NSG"
   - name: Create public IP address
     azure_rm_publicipaddress:
      resource_group: "{{ rgname }}"
      allocation_method: Dynamic
      name: "h1pip"
      location: "eastus"
   - name: Create public IP address
     azure_rm_publicipaddress:
      resource_group: "{{ rgname }}"
      allocation_method: Dynamic
      name: "h2pip"
      location: "westus"
   - name: Create virtual network inteface card
     azure_rm_networkinterface:
      resource_group: "{{ rgname }}"
      name: "h1nic"
      location: "eastus"
      virtual_network: "h1Vnet"
      subnet: "defaultsubnet"
      public_ip_name: "h1pip"
   - name: Create virtual network inteface card
     azure_rm_networkinterface:
      resource_group: "{{ rgname }}"
      name: "h2nic"
      location: "westus"
      virtual_network: "h2Vnet"
      subnet: "defaultsubnet"
      public_ip_name: "h2pip"
   - name: Create virtual network inteface card
     azure_rm_networkinterface:
      resource_group: "{{ rgname }}"
      name: "s1nic"
      location: "eastus"
      virtual_network: "s1Vnet"
      subnet: "defaultsubnet"
   - name: Create virtual network inteface card
     azure_rm_networkinterface:
      resource_group: "{{ rgname }}"
      name: "s2nic"
      location: "eastus"
      virtual_network: "s2Vnet"
      subnet: "defaultsubnet"
   - name: Create virtual network inteface card
     azure_rm_networkinterface:
      resource_group: "{{ rgname }}"
      name: "s3nic"
      location: "westus"
      virtual_network: "s3Vnet"
      subnet: "defaultsubnet"
   - name: Create virtual network inteface card
     azure_rm_networkinterface:
      resource_group: "{{ rgname }}"
      name: "s4nic"
      location: "westus"
      virtual_network: "s4Vnet"
      subnet: "defaultsubnet"
   - name: Create VM hub1
     azure_rm_virtualmachine:
      name: "h1-VM"
      resource_group: "{{ rgname }}"
      location: "eastus"
      state: present
      admin_username: 'vmadmin'
      admin_password: "123#ntms123#"
      os_type: Windows
      managed_disk_type: StandardSSD_LRS
      os_disk_size_gb: 30
      boot_diagnostics: 
        enabled: no      
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2016-Datacenter
        version: latest
      vm_size: Standard_DS1_v2   
      virtual_network_name: "h1Vnet"
      subnet_name: "defaultsubnet" 
      network_interface_names: "h1nic"
   - name: Create VM hub2
     azure_rm_virtualmachine:
      name: "h2-VM"
      resource_group: "{{ rgname }}"
      location: "westus"
      state: present
      admin_username: 'vmadmin'
      admin_password: "123#ntms123#"
      os_type: Windows
      managed_disk_type: StandardSSD_LRS
      os_disk_size_gb: 30
      boot_diagnostics: 
        enabled: no      
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2016-Datacenter
        version: latest
      vm_size: Standard_DS1_v2   
      virtual_network_name: "h2Vnet"
      subnet_name: "defaultsubnet"      
      network_interface_names: "h2nic" 
   - name: Create VM spoke1
     azure_rm_virtualmachine:
      name: "s1-VM"
      resource_group: "{{ rgname }}"
      location: "eastus"
      state: present
      admin_username: 'vmadmin'
      admin_password: "123#ntms123#"
      os_type: Windows
      managed_disk_type: StandardSSD_LRS
      os_disk_size_gb: 30
      boot_diagnostics: 
        enabled: no      
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2016-Datacenter
        version: latest
      vm_size: Standard_DS1_v2   
      virtual_network_name: "s1Vnet"
      subnet_name: "defaultsubnet"      
      network_interface_names: "s1nic"    
   - name: Create VM spoke3
     azure_rm_virtualmachine:
      name: "s3-VM"
      resource_group: "{{ rgname }}"
      location: "westus"
      state: present
      admin_username: 'vmadmin'
      admin_password: "123#ntms123#"
      os_type: Windows
      managed_disk_type: StandardSSD_LRS
      os_disk_size_gb: 30
      boot_diagnostics: 
        enabled: no      
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2016-Datacenter
        version: latest
      vm_size: Standard_DS1_v2   
      virtual_network_name: "s3Vnet"
      subnet_name: "defaultsubnet"
      network_interface_names: "s3nic"      
   - name: Create VM spoke4
     azure_rm_virtualmachine:
      name: "s4-VM"
      resource_group: "{{ rgname }}"
      location: "westus"
      state: present
      admin_username: 'vmadmin'
      admin_password: "123#ntms123#"
      os_type: Windows
      managed_disk_type: StandardSSD_LRS
      os_disk_size_gb: 30
      boot_diagnostics: 
        enabled: no      
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2016-Datacenter
        version: latest
      vm_size: Standard_DS1_v2   
      virtual_network_name: "s4Vnet"
      subnet_name: "defaultsubnet"
      network_interface_names: "s4nic"      
   - name: Create VM spoke2
     azure_rm_virtualmachine:
      name: "s2-VM"
      resource_group: "{{ rgname }}"
      location: "eastus"
      state: present
      admin_username: 'vmadmin'
      admin_password: "123#ntms123#"
      os_type: Windows
      managed_disk_type: StandardSSD_LRS
      os_disk_size_gb: 30
      boot_diagnostics: 
        enabled: no      
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2016-Datacenter
        version: latest
      vm_size: Standard_DS1_v2   
      virtual_network_name: "s2Vnet"
      subnet_name: "defaultsubnet"
      network_interface_names: "s2nic"
...
