---
- hosts: localhost
  vars: 
    RG-name: "rg1"
  tasks:
   - name: Create a resource group
     azure_rm_resourcegroup:
      name: "{{RG-name}}"
      location: "eastus"
   - name: Create virtual network vnet1
     azure_rm_virtualnetwork:
      resource_group: "{{RG-name}}"
      name: "h1Vnet"
      address_prefixes: "10.1.0.0/16"
   - name: Create virtual network vnet2
     azure_rm_virtualnetwork:
      resource_group: "{{RG-name}}"
      name: "h2Vnet"
      address_prefixes: "10.2.0.0/16"
   - name: Create virtual network vnet3
     azure_rm_virtualnetwork:
      resource_group: "{{RG-name}}"
      name: "s1Vnet"
      address_prefixes: "10.3.0.0/16"
   - name: Create virtual network vnet4
     azure_rm_virtualnetwork:
      resource_group: "{{RG-name}}"
      name: "s2Vnet"
      address_prefixes: "10.4.0.0/16"
   - name: Create virtual network vnet5
     azure_rm_virtualnetwork:
      resource_group: "{{RG-name}}"
      name: "s3Vnet"
      address_prefixes: "10.5.0.0/16"
   - name: Create virtual network vnet6
     azure_rm_virtualnetwork:
      resource_group: "{{RG-name}}"
      name: "s4Vnet"
      address_prefixes: "10.6.0.0/16"
   - name: Create Network Security Group that RDP
     azure_rm_securitygroup:
       resource_group: "{{ RG-name}}"
       name: "h1NSG"
       rules:
        - name: RDP
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound  
   - name: Create Network Security Group that RDP
     azure_rm_securitygroup:
       resource_group: "{{ RG-name}}"
       name: "s3NSG"
       rules:
        - name: RDP
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound  
   - name: Create Network Security Group that RDP
     azure_rm_securitygroup:
       resource_group: "{{ RG-name}}"
       name: "s2NSG"
       rules:
        - name: RDP
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound  
   - name: Create Network Security Group that RDP
     azure_rm_securitygroup:
       resource_group: "{{ RG-name}}"
       name: "h2NSG"
       rules:
        - name: RDP
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound  
   - name: Create Network Security Group that RDP
     azure_rm_securitygroup:
       resource_group: "{{ RG-name}}"
       name: "s1NSG"
       rules:
        - name: RDP
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound            
   - name: Create Network Security Group that RDP
     azure_rm_securitygroup:
       resource_group: "{{ RG-name}}"
       name: "s4NSG"
       rules:
        - name: RDP
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound             
   - name: Add subnet 
     azure_rm_subnet:
       resource_group: "{{RG-name}}"
       name: "defaultsubnet"
       address_prefix: "10.1.0.0/24"
       virtual_network: "h1Vnet"
       security_group: "h1NSG"
   - name: Add subnet 
     azure_rm_subnet:
       resource_group: "{{RG-name}}"
       name: "defaultsubnet"
       address_prefix: "10.2.0.0/24"
       virtual_network: "h2Vnet"
       security_group: "h2NSG"
   - name: Add subnet 
     azure_rm_subnet:
      resource_group: "{{RG-name}}"
      name: "defaultsubnet"
      address_prefix: "10.3.0.0/24"
      virtual_network: "s1Vnet"
      security_group: "s1NSG"
   - name: Add subnet 
     azure_rm_subnet:
      resource_group: "{{RG-name}}"
      name: "defaultsubnet"
      address_prefix: "10.4.0.0/24"
      virtual_network: "s2Vnet"
      security_group: "s2NSG"
   - name: Add subnet 
     azure_rm_subnet:
      resource_group: "{{RG-name}}"
      name: "defaultsubnet"
      address_prefix: "10.5.0.0/24"
      virtual_network: "s3Vnet"
      security_group: "s3NSG"
   - name: Add subnet 
     azure_rm_subnet:
      resource_group: "{{RG-name}}"
      name: "defaultsubnet"
      address_prefix: "10.6.0.0/24"
      virtual_network: "s4Vnet"
      security_group: "s4NSG"
    

...
