---
- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: "rakesh-rg"
    vm_name: webvm
    location: eastus
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "Vnet"
      address_prefixes: "10.0.0.0/16"
...      
