---
- hosts: localhost
  tasks:
    - name: vnet1
      azure_rm_resource:
        api_version: '2018-07-01'
        resource_group: 'RG1'
        provider: 'Network'
        resource_type: 'virtualNetworks'
        resource_name: 'vnet1'
        body:
          location: eastus
          properties:
            addressSpace:
              addressPrefixes:
                - '10.10.0.0/16'
            subnets:
                properties:
                  addressPrefix: '10.10.0.0/24'
...
